services:
  - type: web
    name: nexusk-forum
    env: docker
    # 您的 Web 服务可以继续使用免费计划
    plan: free
    dockerfilePath: ./Dockerfile

    # 关键修改：所有的环境变量都已从此文件移除。
    # 您必须在 Render 控制面板的 "Environment" 选项卡中设置以下所有的环境变量。
    # 这种做法将配置与代码分离，更加安全和灵活。
    #
    # 需要设置的变量列表：
    # - DB_HOST
    # - DB_NAME
    # - DB_USER
    # - DB_PASS (建议设置为 Secret)
    # - FORUM_URL
    # - FLARUM_ADMIN_USER
    # - FLARUM_ADMIN_PASS (建议设置为 Secret)
    # - FLARUM_ADMIN_MAIL
    # - FLARUM_TITLE
    # - TZ
    envVars: []
